# Default values for lnd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
# serviceName: my-lnd
updateStrategy:
  type: "RollingUpdate"

services:
  api:
    type: ClusterIP
    restPort: 8080
    restListen:
      - 0.0.0.0
    rpcPort: 10009
    rpcListen: []

  p2p:
    type: LoadBalancer
    port: 9735
    nolisten: false
    listen: []

lnd:
  image:
    repository: budacom/lnd
    tag: v0.7.1-beta
    pullPolicy: IfNotPresent

  debugLevel: info
  # keystoreSecret: "lnd-keystore"
  # alias: My Lightning Node
  # color: "#5293fc"
  # externalip: ""
  # tlsextradomains: ""
  # tlsextraips: 10.28.0.6

  unlock:
    enabled: false

  autopilot:
    enabled: false
    maxchannels: 5
    allocation: 0.6

  prometheus:
    enabled: false
    listen: 0.0.0.0:9092

    serviceMonitor:
      enabled: true
      # interval: 30s
      # scrapeTimeout: 10s

  livenessProbe:
    enabled: false

  readinessProbe:
    enabled: false

  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: "5Gi"
    # storageClass: "ssd"

lndmon:
  enabled: false
  image:
    repository: budacom/lndmon
    tag: v0.1.0
    pullPolicy: IfNotPresent

  defaultDashboards:
    enabled: false
    sidecarLabel: grafana_dashboard

  prometheus:
    listen: 0.0.0.0:9093
    # logdir: /root/.lndmon/logs
    # maxlogfiles: 3
    # maxlogfilesize: 10

    serviceMonitor:
      enabled: false
      # interval: 30s
      # scrapeTimeout: 10s

  livenessProbe:
    enabled: false

  readinessProbe:
    enabled: false

  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

lndbackup:
  enabled: false
  image:
    repository: budacom/lndbackup
    tag: latest
    pullPolicy: Always

  # bucket-url: gs://bucket_name/path

bitcoin:
  enabled: true
  network: testnet
  node: bitcoind
  # defaultchanconfs: 3

  bitcoind: {}
    # rpchost: localhost: 18332
    # rpcuser: bitcoin
    # rpcpass: password
    # zmqpubrawblock: tcp://127.0.0.1:28332
    # zmqpubrawtx: tcp://127.0.0.1:29332

nodeSelector: {}

tolerations: []

affinity: {}