apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lnd.fullname" . }}-scripts
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
data:
  .bashrc: |-
    alias lncli="lncli --macaroonpath /root/.lnd/data/chain/bitcoin/{{ .Values.bitcoin.network }}/admin.macaroon --tlscertpath /root/.lnd/data/certs/tls.cert --network {{ .Values.bitcoin.network }}"

  health.sh: |-
    #!/bin/bash
    # Install curl
    if ! [[ -n "$(which curl)" ]]
    then
      apk --update add curl
    fi

    CERT=/root/.lnd/data/certs/tls.cert
    MACARRON=/root/.lnd/data/chain/bitcoin/{{ .Values.bitcoin.network }}/readonly.macaroon

    REST_URL=https://localhost:{{ .Values.services.api.restPort }}

    # Test for 200
    curl \
      --fail \
      --cacert $CERT \
      -H "Grpc-Metadata-macaroon: $(xxd -p -c 1000 $MACARRON | tr -d ' ')" \
      ${REST_URL}/v1/getinfo