apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lnd.fullname" . }}-conf
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
data:
  lnd.conf: |-

    ; Config built from helm values
    tlscertpath=~/.lnd/data/certs/tls.cert
    tlskeypath=~/.lnd/data/certs/tls.key

{{- if .Values.lnd.unlock.enabled }}
    wallet-unlock-password-file={{ .Values.lnd.unlock.walletSecretPath }}
{{ end -}}

  {{ with .Values.services }}
    {{- if .p2p.listen }}
    {{- range .p2p.listen -}}
    listen={{ . }}
    {{ end }}
    {{ end -}}
    {{- if .p2p.nolisten }}
    nolisten=1
    {{- end }}
    {{- if .api.rpcListen }}
    {{- range .api.rpcListen }}
    rpclisten={{ . }}
    {{- end }}
    {{ end -}}
    {{- if .api.restListen }}
    {{- range .api.restListen }}
    restlisten={{ . }}
    {{ end }}
    {{ end -}}
  {{- end -}}

{{- if .Values.lnd.prometheus.enabled }}
    prometheus.enable=1
    prometheus.listen={{ .Values.lnd.prometheus.listen }}
{{ end }}

{{- if .Values.bitcoin.enabled }}
  {{- with .Values.bitcoin }}
    bitcoin.active=1
    bitcoin.{{ .network }}=1
    bitcoin.node={{ .node }}
    {{- if .bitcoind }}
    {{- if .bitcoind.rpchost }}
    bitcoind.rpchost={{ .bitcoind.rpchost }}
    {{ end }}
    {{- if .bitcoind.rpcuser }}
    bitcoind.rpcuser={{ .bitcoind.rpcuser }}
    {{ end }}
    {{- if .bitcoind.rpcpass }}
    bitcoind.rpcpass={{ .bitcoind.rpcpass }}
    {{ end }}
    {{- if (or .bitcoind.zmqpubrawblock  .bitcoind.zmqpubrawtx) }}
    bitcoind.zmqpubrawblock={{ .bitcoind.zmqpubrawblock }}
    bitcoind.zmqpubrawtx={{ .bitcoind.zmqpubrawtx }}
    {{ end -}}
    {{ end -}}
  {{ end -}}
{{- end }}

    ; Addition config from helm values
{{ .Values.lnd.additionalConfig | indent 4 }}
