apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
data:
  lnd.conf: |-

    ; Config built from helm values
    tlscertpath=~/.lnd/data/certs/tls.cert
    tlskeypath=~/.lnd/data/certs/tls.key

  {{ with .Values.services }}
    {{- if .p2p.listen }}
    {{- range .p2p.listen -}}
    listen={{ . }}
    {{ end }}
    {{ end -}}
    {{- if .p2p.nolisten }}
    nolisten=1
    {{- end }}
    {{- if .api.rpcListen }}
    {{- range .api.rpcListen }}
    rpclisten={{ . }}
    {{- end }}
    {{ end -}}
    {{- if .api.restListen }}
    {{- range .api.restListen }}
    restlisten={{ . }}
    {{ end }}
    {{ end -}}
  {{- end -}}

{{- if .Values.lnd.prometheus.enabled }}
    prometheus.enable=1
    prometheus.listen={{ .Values.lnd.prometheus.listen }}
{{ end }}

{{- if .Values.bitcoin.enabled }}
  {{- with .Values.bitcoin }}
    bitcoin.active=1
    bitcoin.{{ .network }}=1
    bitcoin.node={{ .node }}
    {{- if .bitcoind }}
    {{- if .bitcoind.rpchost }}
    bitcoind.rpchost={{ .bitcoind.rpchost }}
    {{ end }}
    {{- if .bitcoind.rpcuser }}
    bitcoind.rpcuser={{ .bitcoind.rpcuser }}
    {{ end }}
    {{- if .bitcoind.rpcpass }}
    bitcoind.rpcpass={{ .bitcoind.rpcpass }}
    {{ end }}
    {{- if (or .bitcoind.zmqpubrawblock  .bitcoind.zmqpubrawtx) }}
    bitcoind.zmqpubrawblock={{ .bitcoind.zmqpubrawblock }}
    bitcoind.zmqpubrawtx={{ .bitcoind.zmqpubrawtx }}
    {{ end -}}
    {{ end -}}
  {{ end -}}
{{- end }}

    ; Addition config from helm values
{{ .Values.lnd.additionalConfig | indent 4 }}

  {{- if .Values.lnd.unlock.enabled }}
  post-start.sh: |-
    #!/bin/bash
    # Install curl
    if ! [[ -n "$(which curl)" ]]
    then
      apk --update add curl
    fi

    CERT=/root/.lnd/data/certs/tls.cert
    MACARRON=/root/.lnd/data/chain/bitcoin/{{ .Values.bitcoin.network }}/admin.macaroon

    REST_URL=https://localhost:{{ .Values.services.api.restPort }}
    WALLET_PASSWORD=${1-$WALLET_PASSWORD}

    # Wait for rest service listening
    until (
      netstat -lnp | grep {{ .Values.services.api.restPort }}
    )
    do
      sleep 1
    done

    # Unlock wallet
    curl \
      --cacert $CERT \
      -H "Grpc-Metadata-macaroon: $(xxd -p -c 1000 $MACARRON | tr -d ' ')" \
      -X POST -d "{\"wallet_password\": \"$(echo -n $WALLET_PASSWORD | tr -d '\n' | base64)\"}" \
      ${REST_URL}/v1/unlockwallet

  {{- end }}
  health.sh: |-
    #!/bin/bash
    # Install curl
    if ! [[ -n "$(which curl)" ]]
    then
      apk --update add curl
    fi

    CERT=/root/.lnd/data/certs/tls.cert
    MACARRON=/root/.lnd/data/chain/bitcoin/{{ .Values.bitcoin.network }}/readonly.macaroon

    REST_URL=https://localhost:{{ .Values.services.api.restPort }}

    # Test for 200
    curl \
      --fail \
      --cacert $CERT \
      -H "Grpc-Metadata-macaroon: $(xxd -p -c 1000 $MACARRON | tr -d ' ')" \
      ${REST_URL}/v1/getinfo
