apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnd.fullname" . }}-p2p
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.p2p.type }}
  ports:
  - name: p2p
    port: {{ .Values.services.p2p.port }}
    targetPort: p2p
    protocol: TCP
  selector:
    {{- include "lnd.selectorLabels" . | nindent 4 }}
