apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnd.fullname" . }}-p2p
  labels:
    app.kubernetes.io/name: {{ include "lnd.name" . }}
    helm.sh/chart: {{ include "lnd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.services.p2p.type }}
  ports:
  - name: p2p
    port: {{ .Values.services.p2p.port }}
    targetPort: p2p
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "lnd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
