apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnd.fullname" . }}-api
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.api.type }}
  ports:
  - name: rest
    port: {{ .Values.services.api.restPort }}
    targetPort: rest
    protocol: TCP
  - name: rpc
    port: {{ .Values.services.api.rpcPort }}
    targetPort: rpc
    protocol: TCP
  {{- if .Values.lnd.prometheus.enabled }}
  - name: metrics-lnd
    port: 9092
    targetPort: metrics-lnd
    protocol: TCP
  {{- end }}
  {{- if .Values.lndmon.enabled }}
  - name: metrics-lndmon
    port: 9093
    targetPort: metrics-lndmon
    protocol: TCP
  {{- end }}
  selector:
    {{- include "lnd.selectorLabels" . | nindent 4 }}
